# The following properties are required for fhswf (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/

MCR.NameOfProject=fhswf
MIR.projectid.default=fhswf

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain.
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain.
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain.
MCR.mir-module.MailSender=
# Mail recipient for new users, e.g. <name> mail@domain.
MCR.mir-module.NewUserMail=

##############################################################################
# DOI                                                                        #
##############################################################################
MCR.DOI.Prefix=10.48499
MCR.PI.Service.Datacite.HostingInstitution=Publikationsserver der FH S\u00FCdwestfahlen

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.UseTestServer=true
MCR.PI.Service.Datacite.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%/
MCR.PI.Service.Datacite.Generator=DOIGenerator
MCR.PI.Generator.DOIGenerator=org.mycore.pi.MCRGenericPIGenerator
MCR.PI.Generator.DOIGenerator.GeneralPattern=%MCR.DOI.Prefix%/FHSWF.$1$Count
MCR.PI.Generator.DOIGenerator.Type=doi
MCR.PI.Generator.DOIGenerator.XPath.1=concat(substring-after(//mods:mods/mods:name[@type='corporate' and contains(@authorityURI, 'mir_institutes')]/@valueURI,'#'),substring(".",1,string-length(//mods:mods/mods:name[@type='corporate' and contains(@authorityURI, 'mir_institutes')]/@valueURI)))
MCR.PI.Service.Datacite.MetadataService=MODSDOI
MCR.PI.MetadataService.MODSDOI.Prefix=%MCR.DOI.Prefix%
MCR.PI.MetadataService.MODSDOI.Type=doi

##############################################################################
# URN configuration                                                          #
##############################################################################
MCR.PI.Generator.TypeYearCountURN.Namespace=urn:nbn:de:hbz:hag4-
MCR.PI.Generator.TypeYearCountURN.GeneralPattern=%MCR.PI.Generator.TypeYearCountURN.Namespace%$ObjectDate-$Count
MCR.PI.Generator.TypeYearCountURN.DateFormat=yyyy
MCR.PI.Generator.TypeYearCountURN.CountPrecision=4

##############################################################################
# OAI                                                                        #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=Publikationsserver der FH S\u00FCdwestfahlen
# Repository domain without protocol, e.g. domain.
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml
MCR.OAIDataProvider.OAI2.RecordSampleID=fhswf_mods_00000017
MCR.OAIDataProvider.RepositoryPublisherName=Fachhochschule S\u00FCdwestfalen
MCR.OAIDataProvider.RepositoryPublisherPlace=Iserlohn
MCR.OAIDataProvider.RepositoryPublisherAddress=Fachhochschule Suedwestfalen, Baarstra\u00DFe 6, 58636 Iserlohn

MCR.OAIDataProvider.OAI2.MoveNamespaceDeclarationsToRoot=false
MCR.OAIDataProvider.OAI2.FilterEmptySets=false
MCR.OAIDataProvider.OAI2.Search.SortBy=modified desc, id desc

# Set content transformer for marc21 set.
MCR.ContentTransformer.oai-marc21.Class=org.mycore.common.content.transformer.MCRTransformerPipe
MCR.ContentTransformer.oai-marc21.Steps=mods,mods2marcxml

# Define xMetaDissPlus set.
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.URI=webapp:oai/set_xmetadissplus.xml
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.Query=(mods.genre:dissertation OR mods.identifier:urn\\\:nbn\\\:de\\\:hbz\\\:hag4-*) AND derCount:[1 TO *] AND NOT(mods.type:video OR mods.type:research_data)

# Define hosting type set.
MCR.OAIDataProvider.OAI2.Sets.hostingType.URI=xslStyle:classification2sets:classification:metadata:10:children:mir_hostingType
MCR.OAIDataProvider.OAI2.Sets.hostingType.Classification=mir_hostingType

# Define URN set.
MCR.OAIDataProvider.OAI2.Sets.urn.Query=mods.identifier:urn\\\:nbn\\\:de\\\:hbz\\\:hag4-*

# Overwrite institute set uri.
MCR.OAIDataProvider.OAI2.Sets.institute.URI=xslStyle:classification2sets:classification:metadata:10:children:mir_institutes

# Override oai metadata formats.
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,marc21,mods,epicur,xMetaDissPlus

# Override oai sets.
MCR.OAIDataProvider.OAI2.Sets=open_access,GENRE,xmetadissplus,urn,hostingType

##############################################################################
# xMetaDissPlus                                                              #
##############################################################################
MIR.xMetaDissPlus.rights.rightsReserved2free=true
MIR.HostedPeriodicals.List=fhswf_mods_00000530,fhswf_mods_00000617,fhswf_mods_00000126,fhswf_mods_00000598,fhswf_mods_00000084

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,\
  xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed,\
  xslStyle:editor/mir2xeditor:webapp:editor/fhswf-editor-includes.xed

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=fhswf.js

MIR.Layout.usermenu.realname.enabled=true

# Maximum number of publications that can be outputted within toc.
MIR.TableOfContents.MaxResults=10000

# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

# Additional style sheets.
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,fhswf-templates.xsl

##############################################################################
# Solr                                                                       #
##############################################################################
MCR.URIResolver.xslImports.solr-document=%MCR.URIResolver.xslImports.solr-document%,solr-fhswf.xsl

##############################################################################
# Enrichment                                                                 #
##############################################################################
MIR.OADOI.Mail.Address=

##############################################################################
# Batch editor                                                               #
##############################################################################
MCR.BatchEditor.institut.Path2Remove=mods:name[@type='corporate'][@authorityURI='https://publikationen.fhb.fh-swf.de/api/v2/classifications/mir_institutes'][@valueURI="https://publikationen.fhb.fh-swf.de/api/v2/classifications/mir_institutes#{0}"][@xlink:type="simple"]
MCR.BatchEditor.institut.Path2Add=mods:name[@type='corporate'][@authorityURI='https://publikationen.fhb.fh-swf.de/api/v2/classifications/mir_institutes'][@valueURI="https://publikationen.fhb.fh-swf.de/api/v2/classifications/mir_institutes#{0}"][@xlink:type="simple"]

##############################################################################
# Sitelinks                                                                  #
##############################################################################
MCR.Servlet.SitelinksServlet.Disabled=false

##############################################################################
# Misc                                                                       #
##############################################################################
# Persist transient users, e. g. Shibboleth user.
MCR.EventHandler.MCRObject.110.Class=org.mycore.user2.events.MCRPersistTransientUserEventHandler
